# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8b43266b512415f912f67054b024154d"
name = "checkout-ui-extension-1"
handle = "checkout-ui-extension-136"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "milan-test-1.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
